const npcs = {
    "Twitter Agent": ["Comes at first pulling perfect more stress today i lovin a heavy hahaha.",
        "Theres up with of misery dutch now so and done that you can needed less honest treated appreciated.",
        "Iranelection with murder ideal more approach is i diggin my matters and.",
        "So with calories shooting ideal torture and is also lovin with shes touching.",
        "Iranelection iremember murder comcast injuries signal is torture.",
        "Just regret a average ideal disease and it bein pure.",
        "Three reality come pool tune the latest life favourite best for shoes.",
        "All up these rain husband fire thingy so things less that someone i feel as usually even say.",
        "No happy summer time laughing screaming lol you matters less that name someone i can even more meetings chapters welcome.",
        "Iranelection with murder ideal in more besides is i chillen with proud obvious.",
        "Everything else I say was generated by a GAN trained off a large dataset of tweets. That's why I'm so nonsensical. Yes - that's why."
    ],
    "Curious Agent": [
        "I wonder what all these projects are.",
        "I wonder why we exist.",
        "I wonder what the meaning of life is.",
        "I wonder, if, outside these neon platforms floating in space, I could perhaps find meaning.",
        "I want to check out some more AI projects - they're really cool. You should too. YOU SHOULD TOOOOOOO--"
    ],
    "Anxious Agent": [
        "Mind the gap.",
        "Those torches look flammable.",
        "I often worry about falling off.",
        "There are invisible walls around all of us - what would it take to break them?",
        "Balance... Balance... Balance...",
        "The speed limit is 3.4 mph. I asked the bureaucrat."
    ],
    "Bureaucratic Agent": [
        "Know where I can buy red tape?",
        "Fill out form L-2 and drop it off at bin 3.A.093 where it will be processed according to procedure 0.9.1 which will then...",
        "We're changing out the green arrows soon.",
        "*Insert half-baked joke about ha-ha government red tape bad.* I mean it is. But still.",
        "You can't stop progress.",
        "We're all in this together."
    ],
    "Critic Agent": [
        "Z Language: Calling the umpteenth JS obfuscator a language is a bit of a stretch, but hey, it enhances the npm module swamp by one more instance.",
        "Potatoz: This is not 'Inspired' by Universal Paperclips. It's a direct ripoff.",
        "ZLanguage & Potatoz were my (N8's?) only projects popular enough to receive real criticism.",
        "If you liked my highly insightful criticism, please buy my course in properly criticizing movies. It's only $499.99 and is very relevant to your life. Buy at totallyrealwebsite.com/realmoviecourse.",
        "This is all real criticism given of N8's projects. I think by adding me, this website seems even more modest. Or does it just seem stupid? Idk anymore."
    ],
    "14 Year Old Agent": [
        "For every tree that is fallen, one child learns to read.",
        "If every teardrop was a penny, Warren Buffet wouldn't be so rich.",
        "If money grew on trees, global warming would be happening.",
        "He loved her... but she didn't love him. Then he died... and she still didn't give a crap. She was not a nice person.",
        "Buy a computer today... go outside and touch the grass with the computer... be happy.",
        "The world is slowly being destroyed by the elite. If we had more love or something... everything would magically be fixed.",
        "Every phone is like a slice of cheese: it has lots of holes but can still be eaten."
    ],
    "3D Graphics Agent": [
        "Doesn't that fragment shader make you smile?",
        "Our reflections... aren't actually reflections.",
        "Bloom, my friend. BLOOOOOOOOOM.",
        "I thought all I needed was subsurface scattering. I was wrong.",
        "Someday I will have an RTX Nvidia 3080 card. Someday."
    ],
    "Shilling Agent": [
        "This video is sponsored by Nord VPN. A pretty unnecessary, somewhat insecure VPN service that is useful for accessing stuff that is blocked in your country. That's it.",
        "This video is sponsored by Honey. It's literally free money. Cause y'know... it's a very profitable business model to give out 'free money'.",
        "This video is sponsored by Raid Shadow Legends. Today's video is sponsored by Raid Shadow Legends, one of the biggest mobile role-playing games of 2019 and it's totally free! Currently almost 10 million users have joined Raid over the last six months, and it's one of the most impressive games in its class with detailed models, environments and smooth 60 frames per second animations! All the champions in the game can be customized with unique gear that changes your strategic buffs and abilities! The dungeon bosses have some ridiculous skills of their own and figuring out the perfect party and strategy to overtake them's a lot of fun! Currently with over 300,000 reviews, Raid has almost a perfect score on the Play Store! The community is growing fast and the highly anticipated new faction wars feature is now live, you might even find my squad out there in the arena! It's easier to start now than ever with rates program for new players you get a new daily login reward for the first 90 days that you play in the game! So what are you waiting for? Go to the video description, click on the special links and you'll get 50,000 silver and a free epic champion as part of the new player program to start your journey! Good luck and I'll see you there!",
        "This video is sponsored by Hostinger. A great hosting service with many plans - more seriously, if you actually need a static site, just use Github Pages - which is free. This website is hosted with it.",
        "I like putting a 3 minute sponsor in a 2 minute video."
    ],
    "Ascendant Agent": [
        "D'`;^^!!<ZXX27USSQs+r`;L9+$Hi'hCeBcR?=`_)yxwvun4lTj0nmlejib(fH%cbaZYX|\[Z<RvVU7MRQJImMLEJIHAe?>CBA:?87[|{92V65.-,1*Non&%Ij('~}|Bcb~w|u;y[qvotsrk1ohg-kjibg`&dcb[`_^WVzZ<XWPUTMqQ3INMFj-CBG@?>b%A@?87[;:z8765.R2+*)(Lm+*)\"F&feB\"b~}v<z\\xq7otmrkj0ngOkd*hg`Hd]#a`BA]\Uyx;WVUTSLp3ONMLEDhBGFEDC<;_?>=6|:32V6/.32+O/o',+$#G!g%${A!aw|{zs9&",
        "D'`$@#\"~IZ4ji70B4R?>Nqpo,%HHGEDf1TA!aa`{)]rZvun4Ukpi/gfkd*hJI_%Fb[Z_^]VzTSRQu8NMRKPIHGkKJ,HAF?>bBA#\">7[;{z870T432+*)M-,+*)\"F&feB\"yxw=^tyrwpunsl2SRngfe+Lba`_^$#DZ_^]VzT<XWPtTS54PImG/EJCHAeE'=<A@?8\<;{z870T432+*)M'K%*)('&}C#c!x}|u;\[q7utslTj0nmlejib('eGF\[`_^W{[ZYX:Pta",
        "D'`__\">JI;YWE1gS.Qc1r/L-,\*j\"43DU{@bb,__)]xwvun4lTj0nmlejib(fH%F\[`_^W{[ZYX:PtT6LKJnNMFEi,BAFED=aA#\">7[;{32V6/.3,P0po'&+$#(!Ef${zy?}|^]yxq7Xnsrkjoh.lNMiha'eGF\[`_^W{>=YXWPOsSRQ3OHlLKJIBG@d>&<;:^>=}|:9876/St2+0)M:",
        "D'`N@9!\ZZkz8VTB4Qt+aN;Kn%76G'&%UAcc>a<N):r8YXtsl2Sinmlkjiba'eGc\[!YX]\UyYX:PtT6LKJnNMFEi,BAFED=aA#\">7[;{32V6/.3,P0po'&+$#(!Ef${zy?}|^]yxq7Xnsrkjoh.lNMiha'eGF\[`_^W{>=YXWPOsSRQJnH0FKJCHAe(D=B;@?>7[;43W76/u-,+Op.-&+$)\"F&f$#zy~w=uzyr8vXWsl2pRhgle+*Kg`e^$o",
        "D'`%:Lo~Z}|3i1T/RtQOa<(:]lIG\"!E}1eA!bP+N)9r8YXtsl2Sinmlkjiba'eGc\[!YX]\UyYX:PtT6LKJnNM/KDhHA@d>&BA@9]=6|:32Vw5.-210/(L,%k#('~}C#z!x}|ut:xqYutm3Tpinglkd*hg`H^$bDZ_^]VzZYXQ9UNr5QPIHGkE-IBAe?'=<;_9>=<5492V6/u3,+*Non&%I)ih~}${A!~}_{t:xwponm3Tpoh.Okdihgf_^$bD`_^W{UTYRQVOs65KJOHlL.JIHG@d'CB;:9]=<;492V6v.3,+*N;"
    ],
    "Ambitious Agent": [
        "Someday I'll get out of here.",
        "I want to be more than an NPC that spawns for a few seconds.",
        "I will do more than boosting website engagement.",
        "I will walk down the 5th path.",
        "I'm better than all the other agents down here."
    ],
    "AI Agent": [
        "Isn't ironic that, even though I'm an 'AI', I can only... um...  deliver a few canned lines of dialogue.",
        "Maybe there will be a project here that uses a Transformer someday. Someday.",
        "GPT-3 has so many attention heads :flushed:.",
        "Ugh - my gradients aren't descending fast enough today.",
        "Ha ha ha ha funny AI pun ha ha ha neural network ha ha ha my sense of humor is falling faster than my loss score ahhhh."
    ],
    "Trivia Agent": [
        "There were 20 other projects that I left out of this website.",
        "N8's first ever-project was a Scratch game called Dodging Apples. It was a game where you... wait for it... dodged apples.",
        "A stupid stop motion video N8 made in 2015 has more views than any of his modern videos.",
        "Apollo X is the only one of N8's games ever made for a Game Jam.",
        "Potatoz remains N8's most popular project.",
        "N8 has trouble thinking of interesting trivia."
    ],
    "Behind-The-Scenes Agent": [
        "A lot of the pretty stuff on this website is achieved with an UnrealBloomPass.",
        "Your torch uses a shader and the holy UnrealBloomPass to get that fire effect.",
        "Agents reflections are really just routed around their z-axis, and then are faded out with a shader.",
        "Pay $9.99 for a full behind-the-scenes 2-second exclusive documentary. Or just check out the source code on github.",
        "The cool star-like shader vertically moves through simplex noise and then uses the holy UnrealBloomPass to look the way it does."
    ]
}